#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x28555A66D7E1DEC9 (daniel@constexpr.org)
#
Name     : innoextract
Version  : 1.7
Release  : 1
URL      : https://constexpr.org/innoextract/files/innoextract-1.7.tar.gz
Source0  : https://constexpr.org/innoextract/files/innoextract-1.7.tar.gz
Source99 : https://constexpr.org/innoextract/files/innoextract-1.7.tar.gz.sig
Summary  : A tool to extract installers created by Inno Setup
Group    : Development/Tools
License  : BSD-3-Clause
Requires: innoextract-bin = %{version}-%{release}
Requires: innoextract-license = %{version}-%{release}
Requires: innoextract-man = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : bzip2-dev
BuildRequires : doxygen
BuildRequires : pkg-config
BuildRequires : pkgconfig(liblzma)
BuildRequires : python3
BuildRequires : zlib-dev

%description
# innoextract - A tool to unpack installers created by Inno Setup
[Inno Setup](http://www.jrsoftware.org/isinfo.php) is a tool to create installers for Microsoft Windows applications. innoextract allows to extract such installers under non-Windows systems without running the actual installer using wine. innoextract currently supports installers created by Inno Setup 1.2.10 to 5.6.0.

%package bin
Summary: bin components for the innoextract package.
Group: Binaries
Requires: innoextract-license = %{version}-%{release}

%description bin
bin components for the innoextract package.


%package license
Summary: license components for the innoextract package.
Group: Default

%description license
license components for the innoextract package.


%package man
Summary: man components for the innoextract package.
Group: Default

%description man
man components for the innoextract package.


%prep
%setup -q -n innoextract-1.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559454233
mkdir -p clr-build
pushd clr-build
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1559454233
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/innoextract
cp LICENSE %{buildroot}/usr/share/package-licenses/innoextract/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/innoextract

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/innoextract/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/innoextract.1
